### PR TITLE
landing page and table of contents for reports

### LINKED ISSUE #63: https://w3c.github.io/webcomponents-cg/ still points to 2021 report
The URL https://w3c.github.io/webcomponents-cg/ (listed at https://github.com/w3c/webcomponents-cg as the repo's homepage) still leads to the 2021 report. Should it be updated to point to the latest version at https://w3c.github.io/webcomponents-cg/2022.html?

### PR DESCRIPTION
**Pull request by thescientist13**
resolves #63 (minimal styling, I'm not much of a designer 😅 )
Screen Shot 2022-12-05 at 13 56 34

### CODE REVIEW

**Comment by Westbrook** [comment]
This looks like a good path, but I’m not sure it’ll publish due to https://github.com/w3c/webcomponents-cg/blob/4dd38c80f60781b7f655de9e3bf89398512e34da/.github/workflows/reports.yml#L17

**Comment by thescientist13** [comment]
Ah, I see.  So maybe something like this?
```yml
include:
  - source: reports/status.html
    destination: index.html
  - source: reports/2021.html
    destination: 2021.html
  - source: reports/2022.html
    destination: 2022.html
```

**Comment by Westbrook** [comment]
I think… hopefully rspec won’t try to “upgrade” the page. If it’s all set up we can try a couple of iterations to get it right tomorrow or the next?

**Comment by thescientist13** [comment]
Yeah, I'll be preoccupied tonight but tomorrow or any other night during the week I am available to hack on this.  Will get the PR updated with the GitHub Actions change and then we can give it a go whenever we're ready.  👍

**Comment by Westbrook** [comment]
I normalized the status page to the respec spec after finding it errored when running it locally. This should "get anything" up, and we can revisit a "home page" later.

**Comment by thescientist13** [comment]
Awesome, thanks @Westbrook !

**Pull request merged**
